version: 1.0.{build}
clone_depth: 1
clone_folder: c:\gopath\src\www.velocidex.com\golang\velociraptor
environment:
  GOPATH: c:\gopath
  PATH: C:\msys64\mingw64\bin;%GOPATH%\bin;%PATH%
install:
- cmd: |
    echo %PATH%
    echo %GOPATH%
    go version
    go env
    go get github.com/golang/dep
    go get -u github.com/golang/dep/cmd/dep
    dep ensure
build_script:
- cmd: |
    regedit /S artifacts/testdata/windows/init.reg
    go run make.go -v windows
test_script:
- cmd: output\velociraptor.exe golden artifacts\testdata\windows\
on_finish:
  - ps: Get-ChildItem artifacts/testdata/windows/*.out.yaml | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
