AdminUI.bind: 127.0.0.1
AdminUI.csrf_secret_key: 'e4YyBJYHfbaJLUzukYT4RlvjCFdKrvAyGZCNC5M/9ru5ZTCQieZfE6xbEjpAyqgk0EngiSPXZ8Im

  8HWtmTYiXfSO7JeXeaVOf4nCdr483uN0PLEaZ/dx9c+VHzIxNqID9tS8rA==

  '
AdminUI.port: '8000'
AdminUI.url: http://localhost:8000
CA.certificate: '-----BEGIN CERTIFICATE-----

  MIIC5DCCAcygAwIBAgIBATANBgkqhkiG9w0BAQsFADAgMREwDwYDVQQDDAhncnJf

  dGVzdDELMAkGA1UEBhMCVVMwHhcNMTgwNjA2MDcyMTAzWhcNMTkwNjA3MDcyMTAz

  WjAXMRUwEwYDVQQDDAx2ZWxvY2lyYXB0b3IwggEiMA0GCSqGSIb3DQEBAQUAA4IB

  DwAwggEKAoIBAQDFGKkxFbhzwFtHL83X6HqteDS0JhPObqqBXpWIEmwduLIv3r/G

  gl9HuhZHGCgvd2+uergUzsof4ckY+M10qYuhX4CJwxmc1Q+5iIJpiZobLzWQ6szd

  lxIF6XTEhNuXBm6xCCtfPGT9SH90QSl+2gN/SZhxkjgyJ0J+Ty1CLKrTsCyZTDHv

  MbHB7Fkrc2lEaVlYgTI8LEZWr9lO+IxDw14e4mhOuYS/YpzPbrnOvMY1YbJDcfxz

  DwAxeJGKdZBmcoKLB1Cr+Qw06S7aUzHDtUl9IkMViImJsA4xj9pnNVjQEqt5yeo5

  UCjDYQy6o5gDPmjghysg+NVni4rSp0VJ2EORAgMBAAGjMjAwMA8GA1UdEwEB/wQF

  MAMBAf8wHQYDVR0OBBYEFHySH7vYHqo085MmxGysQSJj1YjzMA0GCSqGSIb3DQEB

  CwUAA4IBAQAqvBv8RxNT2rrvfzbz+5I4dFwwgLcWIhamLiTAm3kXlBo2rCsec26h

  WmrTXkZL1Gg5cpla8fBAL9NjCKX6CPncGVB4zp56bokm8zebDWcAHGZD3xh5X+7r

  rb2HxDF88Zh5hfrhSc10WzyIBhEGA051CzqXFZtpjfcpv3JLiPzV8HAn4zQq5mCF

  nvEyogBVXHY640pKH/q6fBOeIezng1raA719/OYE+DTtKJkZpmfcSYGaNHpHbF7y

  NMkN5xMJQhEJ790SE0gGKELaZ7iGcuGErbKzNBwOcH94uFjTJtN/yl0LfV49d1Ac

  /IHM2oE3+CtnkBa2oclARfvZoPQwSb27

  -----END CERTIFICATE-----

  '
Client.executable_signing_public_key: '-----BEGIN PUBLIC KEY-----

  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3rMxd9NF+VEZ3IiZ4fTW

  NOCTrTXh7P7FLnWu9yuvRZcFeE3FlB+5WfmKCIHM3t3f/uyLdlTO0W8V4KlnFPzk

  N6HHDZyePOppVmmWQDZGsHAYbNLeL0pdU00N39+HBqlhWwb5GGbJRQFGM0r3bv3D

  LORISZz2ut1j3N0O9CEnRvoEILYMzfpXUn8m4RArwfzuva5UyNRL9NBNZfL58cC1

  vdT5uTpl0ZRkFsdVrmARHm2OkSUANFd0VfiyPhHh2lD8O37y9Q5PGjkO/WZKXOs0

  VU8pu2EAbDDJMVLFKgYEXfIte1tmjDVGSBu74wjRdCYGkK/SLGAdO5VapPuLoP1h

  EQIDAQAB

  -----END PUBLIC KEY-----

  '
Client.server_urls:
- http://localhost:8080/
Config.writeback: /tmp/velociraptor.yaml
Datastore.implementation: SqliteDataStore
Datastore.location: /tmp/velociraptor/
Frontend.bind_address: '127.0.0.1'
Frontend.bind_port: 8080
Frontend.certificate: '-----BEGIN CERTIFICATE-----

  MIICwDCCAaigAwIBAgIBAjANBgkqhkiG9w0BAQsFADAgMREwDwYDVQQDDAhncnJf

  dGVzdDELMAkGA1UEBhMCVVMwHhcNMTgwNjA2MDcyMTAzWhcNMTkwNjA3MDcyMTAz

  WjAVMRMwEQYDVQQDDApHUlIgU2VydmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A

  MIIBCgKCAQEAwU7dMli7hXBR3CUOD9pcCuUgMMp4N1VhCaCI/oI5J5v2S2w0jgGl

  YEqS97ULngqPba5IeI/V+b53us8f6tgtMVzs/G/iVOqDPkXoPiTwjXOr3EnvVqPZ

  1rNULcMD6agowGK4a3c+4uAYSSsFSeFiz/WDSRFJr6DzhGUdn8RAMTO0jB5CNLM6

  nRVxJobmkCRVzy6i08OuqCjzUfxC3/l+LBqWsUEEe7A9+kvs1aH1J0782sW8Yw1W

  ZzvAtSM7p+4f7v0+p5YW9LhL/NOK+lHoLTAxm/mbxzSPjHSZzQ41uiPQY01eBOk3

  OCkM9gHBI/tCBhcNqjR4+98/R2tlv08oSQIDAQABoxAwDjAMBgNVHRMBAf8EAjAA

  MA0GCSqGSIb3DQEBCwUAA4IBAQCTw7MSrmMQsPxTzzh+hTOrKHJyYBmXWnwRD7/M

  l5fimakObn3EXtV3PReIZeKUNP2j3pMVsVdUCzBY6QzEz/BsfxHHZ6J+o2kQgk97

  FdnKhhfgglM/SHLDSZt71YCqAdMquaX8rf3xDLS+eZENaRE4wN0TcJT1YBBIQbMx

  ERHW3v2iNY+089V/0bb419fjDD+FSQ8ZryIuzcqhkA5NfRPFoWylmAfvxj4qrNjR

  XoEjXx3kCA6kK15Jq+je9067jYafTidZafetnKk/Vbfp0dXUhQKyxGunp3skWpnL

  CeMPgoRG6Ejz8YJWZhwJ884vIpJip4jtJnaRsdEnBNn/3TD2

  -----END CERTIFICATE-----

  '
PrivateKeys.ca_key: '-----BEGIN RSA PRIVATE KEY-----

  MIIEpAIBAAKCAQEAxRipMRW4c8BbRy/N1+h6rXg0tCYTzm6qgV6ViBJsHbiyL96/

  xoJfR7oWRxgoL3dvrnq4FM7KH+HJGPjNdKmLoV+AicMZnNUPuYiCaYmaGy81kOrM

  3ZcSBel0xITblwZusQgrXzxk/Uh/dEEpftoDf0mYcZI4MidCfk8tQiyq07AsmUwx

  7zGxwexZK3NpRGlZWIEyPCxGVq/ZTviMQ8NeHuJoTrmEv2Kcz265zrzGNWGyQ3H8

  cw8AMXiRinWQZnKCiwdQq/kMNOku2lMxw7VJfSJDFYiJibAOMY/aZzVY0BKrecnq

  OVAow2EMuqOYAz5o4IcrIPjVZ4uK0qdFSdhDkQIDAQABAoIBAFi+Fc/n+7kCbxbK

  S2BfaH0aloBWdKyJ33OIZsNxqARp2LD9FlQG92eQPd+c3NsiZ8KjtqaHxTI9sxHv

  VHKmtBvgqDtfAPVAaWgcMrvaHO0IgJHTZpKPJqpKxyyEtWp2lvhWuVCUHNR+BAUQ

  IeLfvptdQ6o/L9ZFHwdIFxSoj/Hnopfd67M7xLnUzTQuRifxnHA0yD4fzgTf0CbO

  I7CbLWYY5D7K5Cbzx3tX6my+5Q6AiC6worTinLTmzoIGu5S6SkbkOfu7PpGxi09r

  Ka63kJgmB9obB5ERMaSh9CRE2uvfpRCmlptAO8/05dpDDwZKkdTDJew332zdw/1C

  oaAJS8ECgYEA5ehdlc0++YWvRdF7TcDQpnqQi1fjG+U8nUylH7iZERztO/VhUEhD

  AuTdZ0BKk94rIq8neN8MO6aRnJKv1WvSWIhb2AxcibuLWHAhc5yG5ZaLtRhe+fws

  n8v9Oj1PM7fOh1ndpxWaUsgL470Gp+lUONo08Z50R2dCYKaFm8WUwnUCgYEA23cC

  W/4SBYnazn5FwFTasw80+icEqXLAwDPlU3/Tzg4VbRtE9EjUuhfTLCKUVAZO1Ev/

  rvFrGq2kv+9u2zAEOEwuvjPHup1RO1scqzlR3LPUkWN5kfJIYPxbwRyZbL/Arhld

  /RgPchtAtGXRDMD1ZTq2oVhWt0GEHeVre+T9IS0CgYEA39pO/OPaFFRBI4bjOwKp

  Zd9iy/on7GpYiYQuJuOzTgFPUBkMxoGFldTHapgjxTQF5gCLO1pZ6960WrJMuE4C

  gidK3eKzW3wbImITgCEBC5x4rTxshZUu0expxIIbkuy+D/XFJsGXAFE9mmHbkDRU

  yAJWmIfDCh8Vd0vMPa60uF0CgYAi5aCdaiAJe2ssjI2g0J1Z/aAJ6uxl2VZm+ZmM

  lnXifQDRMZXcVjxlPuaYTQNS/RHJ1i/Y7JCAVH4u+u6gsdjp7ss7+VXYCa3iB1He

  tCWdN4ckezHYkDMMIPSiF18aGL+Vr3jvhsTl+wll5g7AvWoH57cknrxjNWrBqjpW

  IApUHQKBgQDNG3lppI197GnAeMhWl2DpxVzSPpOLV/6/YL3by8Eyd1VD9ZJuWPda

  HwU/TMatSgZiQM3JwJ3TL0DnNg5V71n5OthIbg9X2r7+6sY+4RklCz4AgqhQN/gf

  JRUr3mVdygGuzZSX/soaixioDYO6ltKCJ/TYENpM+cyYqBV3b2S+aA==

  -----END RSA PRIVATE KEY-----

  '
PrivateKeys.executable_signing_private_key: '-----BEGIN RSA PRIVATE KEY-----

  MIIEpAIBAAKCAQEA3rMxd9NF+VEZ3IiZ4fTWNOCTrTXh7P7FLnWu9yuvRZcFeE3F

  lB+5WfmKCIHM3t3f/uyLdlTO0W8V4KlnFPzkN6HHDZyePOppVmmWQDZGsHAYbNLe

  L0pdU00N39+HBqlhWwb5GGbJRQFGM0r3bv3DLORISZz2ut1j3N0O9CEnRvoEILYM

  zfpXUn8m4RArwfzuva5UyNRL9NBNZfL58cC1vdT5uTpl0ZRkFsdVrmARHm2OkSUA

  NFd0VfiyPhHh2lD8O37y9Q5PGjkO/WZKXOs0VU8pu2EAbDDJMVLFKgYEXfIte1tm

  jDVGSBu74wjRdCYGkK/SLGAdO5VapPuLoP1hEQIDAQABAoIBAFp7Dbc0hLKWK965

  NWRjuIBFWlq+kKtcm7qTn+HWwuCQSm2lk4fqF8GhrF5mdll6Zh7J9qO+M0VOT+I2

  kaYqVYLw3NH/9x6i0ueEAMLYCoJ3GMVmK1WlbiOBJAj4ZYDkYqS8QYqTgGTj7qS6

  aauTuK/NlD0sY+ZqOr+qpP+1VKL2AZdYQDGMs8m8+jM2eLQeyHencteENCATWIor

  +99kw7w0SobZlPsVQQdTnp4Nqz01zAUIkVq67+Mw4BUuYtvViiMbXMORiwwN83P5

  Qs/SkzhJaboke8OWs/LJy80taghlhSOQnfgax6R+sF/VK2ArLBD2N45XoyS0aWRu

  JUW8g50CgYEA8yWp4bfBaycpnGwzWzNzAktzjo+akzb3guIq2ASJYQinGnqqYo6D

  6Q3Wk3SgGPy8HJI9Z6Kn2j64wEMUWZ5fW3ksvmuxka1yTpggnoFkImVUXG5ySg2g

  yfQqSrnhycOpqwJWMBmD97io5GHxqS3LvPw/AZjq2P5jO+0Bg5q/S/MCgYEA6njV

  PJO/Z3V2cQtIDatRvdnh1lZinV3zA1IZge5wzc9NDca4IA9ds5wIdV87uMPRmlk8

  KN4FTECQkXFUCpBB6Fwz6+HIM+L3Cg+j7CDaRZY26RImCyg/LwRqvnWhFAW1R9z2

  n2aBC6bbMlq5YxUODamIH9waFHFsyRhfxdJJ8+sCgYBW8/gt1XYhKM8ztmojSmHt

  xyfbKrXfwb+AGfuyZuTuQ5bm3ElEl6zK0n0THJkIdpGbMh0ti7i1TsrpTtPfPMjj

  QJFkw8Sr0ThYrQS1SpaRymUB7SmIHBmNP3lEYfdCHWv20Q4bg3RzSaF0kyZGFy+O

  NTMfEh2iXk8EpjxtYRDaSwKBgQCcqgHoSNwR96Uc4SnSoE6sqIFCIlQfy59M77VF

  YJkUmtdkRgvOuBWmpbHtIqWXzZcmJ0uQDtDBYz51P6CkskCnTbwPdru7F4JywYKI

  imbtKfIkhtDOkaSt+KiN+7CV3T6D9rr+RJIiw+kf2wiVkILkVAs1Jm5yjFrgfp23

  Ysuw4wKBgQCDAgKXHTUTi24OeYv//5tz56+XINuSk7x7rN0QVzaBygLJPDqZiggU

  eLLkHk7jNVL8UbFzcacuS+RweWDLKCh0LrEtqc9B49AwwNHxte0OFAywFjHM8K+3

  egwwp+XqTGQYKsyQNf3jDu3C+dZ1bNpSfYfn5F3fo8Pw3be3Cfaj4Q==

  -----END RSA PRIVATE KEY-----

  '
PrivateKeys.server_key: '-----BEGIN RSA PRIVATE KEY-----

  MIIEowIBAAKCAQEAwU7dMli7hXBR3CUOD9pcCuUgMMp4N1VhCaCI/oI5J5v2S2w0

  jgGlYEqS97ULngqPba5IeI/V+b53us8f6tgtMVzs/G/iVOqDPkXoPiTwjXOr3Env

  VqPZ1rNULcMD6agowGK4a3c+4uAYSSsFSeFiz/WDSRFJr6DzhGUdn8RAMTO0jB5C

  NLM6nRVxJobmkCRVzy6i08OuqCjzUfxC3/l+LBqWsUEEe7A9+kvs1aH1J0782sW8

  Yw1WZzvAtSM7p+4f7v0+p5YW9LhL/NOK+lHoLTAxm/mbxzSPjHSZzQ41uiPQY01e

  BOk3OCkM9gHBI/tCBhcNqjR4+98/R2tlv08oSQIDAQABAoIBACvcTwgbZgDy6UAA

  EF68duHp9xHa/sffUXMzv6GvvnQkSQ/37zzBVtqwUQRvScGEN+L1BnCEglJ2SwhR

  8rYActCeew8T+9C0nS7GAdoH26TcuAP1qp6H8udqLRFtDDg59XUhcSLBHb2whxIi

  9sI6p4bz9+PeTk/RPy+tGbmkd8Qxx0hFEXmZbCeNP8/Qn3I5GsAFj36z+i7qznUj

  AIVAl3LVgBixybOjt8Yw9ClcMwEEnaMXDl1xefR4r0OVI29zzaQDQMk9asC64sTI

  W4sySfgKDz3MX5ER1RbIa0ir7f5wvAu0MYfoa8vDlA5O4mRe2/vdd3+EsUr+H/fl

  wOkcR+ECgYEA/p9fVeFicHFdvWYBl+x7DULdSDo/Z3mvaleMQBSU6bOpSol15mep

  l0KtVHbP4uoa9/q6IGunSYx+Y/zoAVT5JegcCJteFpNO3igN5qOdkJBvo7cUzGCW

  Cm/9av839Wu9fxUsI76THD67JyKFTIwzx4X8waBQCsWyiXqHrHI6RPUCgYEAwlqT

  tzhf4ASl19F0I3KEhyj6E+giKrDraV7z/mIDOreBU5+vzmm8kHEFm+CEzNaRl96N

  h5L/l3pAPeYNlpdIWf3GPMDg7Hn3x0pfGT38QAVa9WX8KnKuQKZ5+HyFzqQE1T11

  8WGJyuIGxx1t6cblDJ3CBmaUSzwA7k1tkxn24YUCgYEA/bSlVLg30txS0AZU7iEW

  1zbZsD9BsAQCsk47lBot6tM2iut+y65cwDgS50dfirVDW/W7AdTiohlYUp7MOY+G

  lau6SyUsUghDnH6Co15CAKq6YoFpOt++gPXnp3ZYNrU84uSgz5jzkkA7URpHgedt

  LJCoMfJf7uvgIrYxe7VxtAUCgYAIbBRqpC7DbnAhYho+TwAfO09a/Xw9jV0mO88m

  /uhU6w7XqNvdfgeF2t/7WUdn+QRmKGbJsT0SO2H9TLLaC8Q+4hhtGY6lsMNkB30H

  gwAjZhgC+mBrFn0moBA5DGxgAAuVkgxCYY+vEwxoJIZW0x+p5Ew8KsXSXM9NhF1z

  OnTQYQKBgF2bFzUp383nPv+/JIHYZNzao21CdepdEXygeCHL/poqKlZKXmfKp95R

  OvZCAlfl/7VXycCwJa088MNL3xghU0tcsgNZEBBbl2/mBLmF/4XiWZ9f9+I3HiBJ

  LzkzTeUqWLEfq+QBzqYnbWmCCIYYEZ6+/Jxawd7gGj7iKISuNJOC

  -----END RSA PRIVATE KEY-----

  '
Server.initialized: true
AdminUI.template_root: gui/static/templates

AdminUI.document_root: gui/static
