PrivateKeys.executable_signing_private_key: '-----BEGIN RSA PRIVATE KEY-----

  MIIEpQIBAAKCAQEAxFQH8HfJQEg1hHRePi4r2jJ/p8ZaEavy7INhF1R5LWv2eHpO

  FdFbafXeoaIUirDY9YtY9qTXdW2jbQfBsHji8GQ5bbd7GNv6ij2KRNnEAmxmrYrn

  RdesoI4vaCx38c5nXUpdTG0cVUcX6dhcehA3oQ2WSjt+8S7dqDP03YCWtgY/5bBV

  A6mFxLeu8L5es8LcBMrXvaeAIJ50wYRBnwkGAerx2XxZqLPokfKnrixC2ahvB5pO

  CoEG7QsUvuijkTXLworaLOtmy5oSGyYma/cCs2sOryo81cgSXHK5A5daMjNMNoke

  Mrm51NK2dx4bW59FjEeplXuguKaVQRh8Jg3v0QIDAQABAoIBAQCas0BCSpFJVtzc

  zzlHs+gYGjyevlxQmnZjya5izMxjbzQagP0wkfR/TR8tq+KV2n5LFY93YjLotAjX

  rAoCfW8NT1w1SSP1VblY3t8qG5Io+rP5wX81eJntNbzDUG7/Gc43I5ba1wtBYzDD

  shpEkKzU+jjXq4P+lhhRJwem1mFrcaXszF9V/LOqKPP+REaNKL6Dh/qy90T9Inf0

  CakqKo7Cxd9E3cpu+0ETuFSmARQRHse23Yw/dRosO6oQ1Yx3D09NXYTM7dXm+AM2

  aEFoDXmX2KA2A1zNPLb63FbyCj2HuIeDUw3kwHSobZEfSb6dmtXgUZ4x3H6D2ahX

  28+sv+GVAoGBAOGOuA3dxjVPmRDWwL3ML+PgWFqZbr53H/bfZLH+BYrzxAzyBHAk

  RhQqAJm9Bd/oYZGaUwXbIm11gK0dwsYvvyvkBEnM4ZHE69G00H2TbfnzyzhMn+qi

  yF+KZbD7Ya3YpoAOMke6L7vvPJbtf8qnXW4mCmw18Azng854UeiQgtXjAoGBAN7T

  aBMGcEqwGTfkC0bh/uQxXQ6p0PDfmIgxJQNZHUEJ0OynWvcKvR3S5G9XZUjNOR6C

  EWzfvl3QZ/HzWg8HsBFiFVkp2NR93pbc5+48kwAG7JTFmWbxSszxUKUcuNh3C670

  cDuirefIaqKQkbgfImZaMMZIFrymBXaIbdzqK/G7AoGAMk6bnHQfVhqXwBq1yF83

  OzL5YdOg0JhPJ8exdMV8RP6TdnOwK7bbbnnjwmZXXhY9VLU/2SmD5zfy6CmgHIXf

  tJFZp4Aru1BZbF9QtQFh4QLQC5GDhVijKjP69FtM8PJGSH9iFX9gUCFOuTblbrSf

  cQbJAlORY79rNWy+kAlTNRMCgYEAlNFovtwb/yXhkdxyU6L4U3tMhVCRRW5wNvVr

  nPLVgOyHZqbXMAsyB0skWeBqutalgWSpMqe0Qn/ADG3VBhjCVLnHPEegkzqFgQiE

  ti4ql2gIdcwLCh+5L2szyzKFmbzYRr7mfk3GC/lkjrIzQF864FT4IlVfKhtPpryz

  c0nKk6UCgYEAkDKhnJvLabrWLVHI+tOeCbrJFs2UETwIDCmU7nZ6ZQRrtFH/z96I

  5PiWCGOJT16bhWWFcJU1m+GT3IKIsgcPUo+VqkBh03uKs2pR58mPit+P5C+Rzkke

  3X7H0N3b/J6lLbeTR0Fu32W6iEVgSHou19lcBmxp0tzaU1PirsQ7bI8=

  -----END RSA PRIVATE KEY-----'
Client.executable_signing_public_key: '-----BEGIN PUBLIC KEY-----

  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxFQH8HfJQEg1hHRePi4r

  2jJ/p8ZaEavy7INhF1R5LWv2eHpOFdFbafXeoaIUirDY9YtY9qTXdW2jbQfBsHji

  8GQ5bbd7GNv6ij2KRNnEAmxmrYrnRdesoI4vaCx38c5nXUpdTG0cVUcX6dhcehA3

  oQ2WSjt+8S7dqDP03YCWtgY/5bBVA6mFxLeu8L5es8LcBMrXvaeAIJ50wYRBnwkG

  Aerx2XxZqLPokfKnrixC2ahvB5pOCoEG7QsUvuijkTXLworaLOtmy5oSGyYma/cC

  s2sOryo81cgSXHK5A5daMjNMNokeMrm51NK2dx4bW59FjEeplXuguKaVQRh8Jg3v

  0QIDAQAB

  -----END PUBLIC KEY-----'
CA.certificate: '-----BEGIN CERTIFICATE-----

  MIIC2zCCAcOgAwIBAgIBATANBgkqhkiG9w0BAQsFADAgMREwDwYDVQQDDAhncnJf

  dGVzdDELMAkGA1UEBhMCVVMwHhcNMTgwNDEzMTQxNDQ0WhcNMjgwNDExMTQxNDQ0

  WjAOMQwwCgYDVQQDDANncnIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB

  AQDcSW28V3Hq/81TqUHgjStitTUPQbP+EV2XXhyjeZZDJ2kWVO1PsUT7+IrmfTnF

  BBGVPViEytKobna+X1yh6X01iS7G2c6Sn0U+WofSnUyZI7FxToHrsKHxs2i7U/er

  lION6JvKoVKX0BCbWs67XbQMwB6/8V+D9MQjuQkbR1olPAuSicPFOvgTWvCf93K5

  kg0GbZXqGpgqR830eHT2d4D87P0kswuEF0FC4XxZSbl3N9XobMeJ0I5K4WuREMuU

  QWmIo2Ceyr7HvhozOgwN9tgtab5TvjHSis5/m6/5l0DNXcPGWSJnGAumzJ31QanV

  bMxMP85OfV6zaRtTm7ZzvzT7AgMBAAGjMjAwMA8GA1UdEwEB/wQFMAMBAf8wHQYD

  VR0OBBYEFOAJGWmAH3see/tB8yKaVz1xQv1sMA0GCSqGSIb3DQEBCwUAA4IBAQAH

  Q7emL6VCGqYg7jY05ms5bjrycAgb5azXFfy+Qm0iQOTTowgaqqylSKrZNDA+F4FT

  TS/xZePzWpO1/xRncsg/FDPT1kuzUCsiP3aOxm5R+MPo/sR2bJcFa9Gr+I/LNuiZ

  xgVVk/BJbEicnzFnmyHKtATAyC8bCYhngWrkraMoN/gDvVTiPUzYSW0/p/b/74Kz

  unYmefJq8qMi0PJzXzKbRSjioKETpODT9Eei5ni3p76LpHcGMuAvAHBqsYbbt0Bl

  hUft0UdHLxPqi0jBmIhKi8Q1CGOyvIXIRwA/W7zEd1nPI4z9tQuNKdqI50VH5Mih

  ItgybIt5e3PhIGaoCPR6

  -----END CERTIFICATE-----'
PrivateKeys.ca_key: '-----BEGIN RSA PRIVATE KEY-----

  MIIEpAIBAAKCAQEA3EltvFdx6v/NU6lB4I0rYrU1D0Gz/hFdl14co3mWQydpFlTt

  T7FE+/iK5n05xQQRlT1YhMrSqG52vl9coel9NYkuxtnOkp9FPlqH0p1MmSOxcU6B

  67Ch8bNou1P3q5SDjeibyqFSl9AQm1rOu120DMAev/Ffg/TEI7kJG0daJTwLkonD

  xTr4E1rwn/dyuZINBm2V6hqYKkfN9Hh09neA/Oz9JLMLhBdBQuF8WUm5dzfV6GzH

  idCOSuFrkRDLlEFpiKNgnsq+x74aMzoMDfbYLWm+U74x0orOf5uv+ZdAzV3Dxlki

  ZxgLpsyd9UGp1WzMTD/OTn1es2kbU5u2c780+wIDAQABAoIBAFRDbkuGM5hN40/m

  RcHMnlTyteoxGtXL9L4LDO9nehgUAjm9oM1EJPwxdYh3TFrVlJg+0BZzsyMkph1q

  QvfYZcHNyOvdswwZCpawcJYa/4rwwVZzTnVGqpvXIe/OTcX/WFc3LCjVjs9tknyq

  vrujO1VJRDnt7bh/L2vuwtIBeDUXTiwtnz9oPLTOD7muJztCY48qyqKtdkGAXNlp

  X5qF+yBviFp34v0Plna84DkW4ThGxnoGbO1Z/NTUjMxguMRm9zRGe1q2SYh5U4WA

  BJkRTXRiGVnbAXdQqQGJL7gdGHApgVQfj/QnSGOaqnyaQ3UawiYlxM9mQUfCCfV3

  hMjY+NkCgYEA8gAlILtmdgOVrcVY9YgrjqPgaNVGQrKrgpVUpX74TOuvwAk4ZNU2

  TbYdogE2bPlfqa4QyCG2dimYvif3BQrsPq9Hn3vW/BREJcoLiLgEyEk16acIXhCD

  mKMQTj3enOUMHH/xMP3I2y83xXnIyyhPMswszCu6N8WAnSfi+SvjxaUCgYEA6Qe4

  AHSufQGejY5ZKXOtzf2YCIStrszxwObXqScyBqvrypostbnE0ppszC48jSa1AXu8

  hS8Hajwgei25UDDCFJW381NcH2/gJ5WEEQ3uzzPpBY8ffEz4BauBXyBPPQ0sieZA

  sCFQSWKV2w2OAfbqCZ3kwmwspLVHyD38VsqKTh8CgYEAkOtBUJ6otxdidRNvOGn5

  G4xLgLvnPV3dk291pz2n1/hz4N4kpU2BHXxntnJfc1bK0MPqTM7Tg2NZktY/+QcX

  flpc28a/cWl5fd/GlHMOehpNbMSYICxngep0g0ZNn0sSu6Zqe1ofBBL8pQdPFUno

  U5UtZn7xHyDo6jPOmkSMO/kCgYAwQ98CiShSz/ENFLy27zTCg5HnwcNPfzdbYvSs

  HmgoJZey4Pf9s7pmfIGoULNN8QRwiDZlx3XbtRRs+ed2CoNITDJLfaqJAF0HFdrC

  xYX++Jt9AUXeMvr0Aa/MCh8fYAknjr87O8srR/YN5uLQ2VlkIIXvFwSwILP7b4tC

  VrUKtQKBgQDLfO4iQcBl+OJ4sBpM8nkq7y73COP8y6AagpqWHMNkKPwvtX1mfm7J

  TU/Qdst+f1EA9RWES2a89AjVBBPBpoDN3jonsGREkAiYt75bE6VsbxTE81WX2OdV

  i4QBC2XAHhShQf5RyXfNBxHRLSfpgOPrXNQUD3ChT9Cip1VWz8ULhw==

  -----END RSA PRIVATE KEY-----'
Frontend.certificate: '-----BEGIN CERTIFICATE-----

  MIICuTCCAaGgAwIBAgIBAjANBgkqhkiG9w0BAQsFADAgMREwDwYDVQQDDAhncnJf

  dGVzdDELMAkGA1UEBhMCVVMwHhcNMTgwNDEzMTQxNDQ1WhcNMjgwNDExMTQxNDQ1

  WjAOMQwwCgYDVQQDDANncnIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB

  AQChMhGE5PJdJPGlDL1LOI8lw52oIccv32Wgj1i9HxYartQVTsLmhV0h1X93B6vT

  RhaUyFZK5xLIkcV9P+jMwqHnKx+EdUGkJ+JezSDGQbQQQjNuuVeW1LRvkas5GBaW

  4BRkJXMn7D9vEO8tiC/LUguMpXlVAaRkukwSQdR0lcMD1daAlpiCG2Y5n5wpQ/Zg

  fZcfjiUuleKxTH+Z7VNnyc+I7d7Sbm1oUXI0rsx6i4UX/455yaW3Lcxs4nPnAQMs

  klHaUKRsOmmTg2m9cqo/H38/EjbpXKsn+EtufpmBvsEwgckwJCAVG3ZlhY5ywYR2

  dhrL82+3clAACkmk966JRTJ9AgMBAAGjEDAOMAwGA1UdEwEB/wQCMAAwDQYJKoZI

  hvcNAQELBQADggEBAEryRzpr1OatAfMLYc91N5UzHyAmqZySrvj9XNvHxebU67mu

  9Rl6+XmlbfPyP/Fg41dTLoHBeePfo1MBZ8Jwu8807xB5hT4pTUvFKU9n+Y2fE+dk

  gCcyLpn3jnJ+ioookbm3O363jxrdm8v3tpiD9T0gcG3x8FsTIvm0c35SkneOrWIB

  UA50el8X5sbKypaQRhuoxqxZR82S3vJYSfc0++qck5R95pLbPKFLubDezJ5wKBzL

  JBN9kieYltQKQ41A94pIMoYK2znl95oER+GiwLAxG/q6zyTHTNn2+WRGVStQo8ZP

  np4S042wfNesZtm8G9BArfViheFzLMIb3iUJ8qU=

  -----END CERTIFICATE-----'
PrivateKeys.server_key: '-----BEGIN RSA PRIVATE KEY-----

  MIIEpAIBAAKCAQEAoTIRhOTyXSTxpQy9SziPJcOdqCHHL99loI9YvR8WGq7UFU7C

  5oVdIdV/dwer00YWlMhWSucSyJHFfT/ozMKh5ysfhHVBpCfiXs0gxkG0EEIzbrlX

  ltS0b5GrORgWluAUZCVzJ+w/bxDvLYgvy1ILjKV5VQGkZLpMEkHUdJXDA9XWgJaY

  ghtmOZ+cKUP2YH2XH44lLpXisUx/me1TZ8nPiO3e0m5taFFyNK7MeouFF/+Oecml

  ty3MbOJz5wEDLJJR2lCkbDppk4NpvXKqPx9/PxI26VyrJ/hLbn6Zgb7BMIHJMCQg

  FRt2ZYWOcsGEdnYay/Nvt3JQAApJpPeuiUUyfQIDAQABAoIBAGz32s36szhyNAR+

  QyypdGN0BIzXIL7lBt9uZ++ZJyksjGRHFQwelaG8oOlHP0mYdMVpVKRX5uO9X0LX

  RDm/TRFnnmu9lH0zFR0/D+vWGLJw/jHYizSEX+GYGKaE+ShPHJnCk0EmvI8JZJZk

  HOMWeIZAinADpy0Mn0YsSEHzx5w8DIYAXwSwYL+QIX1KIDhdfTPM5sqqEZDT7IYS

  wC8bXZQvBIxXhmLayhFAoSAVUjswpZEQt4nsdjbzNRt3K1gPIgv4iFpw5VchXHOP

  V7NVBPEs8gD9md8F0jtc/39/I/K+fZCyuMUzH8eLS5q0fP+O1wI/Zf8avc2prsiH

  Nf4XhKUCgYEA0Ar+K8g2udYFK7ILRRjeo6UwKvWgtaVae8TfOHGTBT+aTFa26II/

  usHQjmeKxH4z+LXTIPe5GkXc9KCpMnjqpcQLgD1sQoK1BbREzUYut4v690qya8JR

  kvtzjvFQNa/zDzdlvSjJUHKROnzg4tNw0QK/UUbXHc3J5iW1QfKEm0cCgYEAxlqG

  Ngt+ToOBp88GvEGA1iyScRkYsz6c/V3CN1uL5WgyatdobpAjRBmpwVOEHc8bfXCr

  7vH4dDYkHdR0hIGxN65EbEYwYXY/YMb9J9bQo5tLylYP1SD+hBE1N/Hefi2Jb/vr

  jyVF967ytwZxjhyBpzpQLuHbwLZQVZ2/DKp1nhsCgYEAlf+XCtIsQwkAaWTRo1wv

  CiZL+G1pFg7Gkn57wyKAMkSNZ4UOE831TR341PPqpYmoxyWxuA9kMoE0slw0IeP0

  qtgSwr+Gkt3Szu4OvUJg5I3UwP/mbLOKRUNvKhzrDAp0YQA8JoqFu68e7uCi9Ggm

  60vjzSIab660Z2/ApG/LFHkCgYEAgx1ppCX6yvmA5iUiZaTC/lAeSSZ2vl2ANrcY

  X7FjCzTSRu+294bN2QFBxipnpbC2kje9X0iRnHgBbbp3fvOf6peGYTAQYQxiHp3K

  z9/esJdCBTDYbGDP/QrG7AE0uqFtPRoAfvH7ixsZE8TtoSvUxG72e9cOhRe+iKmq

  lTvEXcsCgYBd9U7KA4OX4LuwpyhGIc00ajllx0Ii4CGOZBbs5h9o9x42cw2ybXcP

  2VaO4I+cZQUF4v46n30CXyhZgm2EBlI9lN0g/epUSaUjpeVekYP7WK25ERZbFYgS

  siNeKoiMJubBemCxYKqNBaLW82esPS7tqqWQLMWa6T6KR3uRiQ+ZUQ==

  -----END RSA PRIVATE KEY-----'
AdminUI.csrf_secret_key: k&w1ohM1eOe190ExDg$bqwIUzpj4dCF7Nf9F7,9BG9UH#Qjg_7SHzpFC64giFK,h_cm
  k-RzfavQi5APZHkFvmr53MaIekodsVQi
Datastore.implementation: SqliteDataStore
Datastore.location: /home/mic/projects/grr/grr/var/grr-datastore
Client.server_urls: http://localhost:8080/
Frontend.bind_port: '8080'
AdminUI.url: http://localhost:8000
AdminUI.port: '8000'
Logging.domain: localhost
Monitoring.alert_email: grr-monitoring@localhost
Monitoring.emergency_access_email: grr-emergency@localhost
Rekall.enabled: 'False'
Server.initialized: 'True'
Client.private_key: '-----BEGIN RSA PRIVATE KEY-----

  MIIEogIBAAKCAQEAxuvw3T61UDhM6DzWGPDZ7/ER/sZOFjDwNXVX3pDqMKagjot9

  NspSKWf38pjF6b8La+hvFC8SJ6oMy1f3569uaoBZlEFzUaCK8crxQJ35NcgOmlzJ

  4a9Q1Eagy2pw2Cmj7a3roN3zAXI3TVYGDySLV3hb+iFP44VmxFN+CYXLIOSNlQSE

  5du2CRoEhgMSWjwwbbdL7MSjAThBrNDQ/HjugzTs5KYy23OBXuEVIriQbjtFS3yw

  rY5k2jYh6jxVyJKXXve3iTOuVuiLXfVnZHTpPED7/2ujfdr9SgD8BWJeTN9a+eRi

  ZQZKsQo7WsXLcvA64BbIUZG5+7tknTMWFD16vQIDAQABAoIBAAo5Bd/Y4SiGPC2T

  Ms2FUy3pjasyNcEeMroMlb9yYxas+YNZ182BCEfod+2XvFQO5V9eSpcW9C/lpVKt

  6qeVdG80uWXNF0gSoBFdBJj1hWEmLtnv+tAGWnkOSCUsCzCQs0P7tChIP7zLSdxH

  l3gfwKl2HgP0wk5HBMkCIXAL2CyQeyRcmKqERvDULKjlrHNxIdGb7huAZbSWpD33

  y7T54apQROZAPcULj5DDyUJ6fwxSnd9Fg+w+avbBPbNwWISLDFpopWzlsuHgsyx0

  A4J7QUtczGsHfaEpZTxCxrSeaAEoJvdzWse/YHbRdn7eU4bbmKW9S/ajwCbnh8gp

  e9ZzsQECgYEA4tb7GfFdHAr5diQOWtZxQwREHMhW/SqFhFnY9PtSmSGRzDxmJXBO

  UDL3A766xD6Z20/Y3vJWIkn+rOiZz7dn2hQumQiTJI0yH5lLmhELd/cvkfAUgDqc

  6KtnzWbaElwVug0AWmHHx5n+c77cufz9tSqpWqbxiNNFBeD/e2J4HNUCgYEA4H41

  bNjBYQ2zSxvZjhSy0AQShYhENPc0MlUX9cn/hRm8ugE/I4P5qxDne1PlW8ghjRuc

  R5B5/hDPIysh6z6AaPZ9uvb25tsTEpjxjs7x+PnPwj55I9I258zPrvgjnNkPjEfs

  +52IEruwKheXZ2naPKNXaICws7FNupP47MohOkkCgYAwwjMRPX9dEsLScSegwO1x

  kU4uvaVtH6G5dDKdXhRAFCYpt2XhcEV1Ga9c37d3jVk2+e/M5Fw9XJhghFLjgjHR

  f3sQq/Ys6ii3ABVvFXDYpYpVHTza3z5xCL70OMJxJdgJuNe1lcUCk4hNSt5ZIBdM

  xNHISZArb/YrMFTaKa1VzQKBgDLFmIOjiijPFmu4Qr3VhJNzOFUm+nYYKp/vitm1

  86pApeRTf9oicQb1bcUAtnDJlHz7b57n2A9T8eT8TlGL8zLJ/KmaTUDs7yVXndo0

  h5lNtmUyB+fIFU7bjWT/Dd7dYJzTb4+Ak1PZSwBaEY377LWmI5Co+k3JndDCwpub

  I2SxAoGAVFoSGzGGIMlLIzzrzts09IcpsFWyx3gG9UUKIuYLP/Qo9Ps0MOL6qXq3

  SxecJK/L/zQTxtyO6GEyB90LRRxnbWE4Ai+G6FnPXzTYyF2pOuLV9g3BSoKyyeAC

  eeOklyZabh8qEBYkQKgcMDsFubHJVn6xnn6zGOyj1h5CSoD1nGY=

  -----END RSA PRIVATE KEY-----

  '
Client.server_serial_number: '2'
